### ISSUE TITLE
Support for custom error handling

### ISSUE THREAD

**Issue by gryphonmyers** [brannondorsey/host-validation#1]
It would be nice to be able to catch the thrown error in order to be able to customize it (e.q. form a JSON response body for JSON APIs). An example of this can be found with https://www.npmjs.com/package/allow-methods AFAICT your module does not currently support this pattern.

**Comment by brannondorsey** [comment]
This sounds like a useful feature indeed. I'm a bit swamped atm, but could maybe add this in a few weeks. In the meantime, PRs welcome :wink:.

**Comment by brannondorsey** [comment]
Hm... maybe a nice place for this would be in the config object:

```javascript

function customHandler(req, res) {
    // craft a custom response in here
}
app.use('hostValidation({ hosts: ['trusted-host.com'], handler: customHandler }));
```

`config.handler` would be undefined by default, but if it was a function it would use that one instead of it's default.

**Comment by gryphonmyers** [comment]
Personally, I think it makes more sense to make use of Express' builtin error handling solution https://expressjs.com/en/guide/error-handling.html

**Comment by r0mflip** [comment]
Imho, the custom handler in the config can be quite useful if you don't want to bloat the express' error handling function. A custom handler can be registered inplace, idk, but both are really useful to have.

**Comment by brannondorsey** [comment]
Support for this feature was added in v2.0.0 via a `config.fail` callback.
